[package]
org = "daneshk"
name = "social_media"
version = "0.0.1"
distribution = "2201.4.1"

[build-options]
observabilityIncluded = true

[persist]
datastore = "mysql"
module = "social_media"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist-native"
version = "0.2.3"

[[platform.java11.repository]]
id="wso2-nexus-snapshot"
url = "https://maven.wso2.org/nexus/content/repositories/snapshots/"
