[package]
org = "daneshk"
name = "social_media"
version = "0.0.1"
distribution = "2201.4.1"

[build-options]
observabilityIncluded = true

# [[platform.java11.dependency]]
# artifactId = "h2"
# version = "2.0.206"
# groupId = "com.h2database"
